
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140902 (SVN rev 60)
//----------------------------------------------------

package ar.edu.itba.lang;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int MINUS = 4;
  public static final int INT = 9;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int RIGHT_PAREN = 8;
  public static final int LEFT_PAREN = 7;
  public static final int REAL = 10;
  public static final int error = 1;
  public static final int TIMES = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "TIMES",
  "MINUS",
  "UMINUS",
  "DIVIDE",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "INT",
  "REAL"
  };
}

